packages:
  - "packages/*"

allowBuilds:
  esbuild: true
  electron: true

catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.2
  vite-plus: 0.2.2
  solid-js: ^1.9.7
  typescript: ^5.8.0

overrides:
  vite: "catalog:"

peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
