import type { GoalSessionAction, GoalSessionRecord } from "@relay/protocol";

/** Optional Playwright spec export for an acknowledged goal path.
 *
 * This is a migration aid, not a verification claim: an exported spec carries
 * no Relay evidence and still requires actual replay acceptance before being
 * labeled reproduced. Steps that only Relay can verify (exact configuration,
 * account fixtures, review gates) are emitted as documented comments, never
 * silently dropped or faked. */

const HEADER = `import { test } from "@playwright/test";

// Generated by Relay from an acknowledged goal path. This file is a starting
// point for teams standardizing on Playwright; it is NOT evidence. Relay's
// exact-configuration, account-fixture, and review guarantees do not transfer
// automatically — re-verify against your own fixtures before trusting it.
`;

function selectorFor(action: GoalSessionAction): string | undefined {
  if (
    action.interaction.kind !== "identifier" &&
    action.interaction.kind !== "ref" &&
    action.interaction.kind !== "label" &&
    action.interaction.kind !== "fill" &&
    action.interaction.kind !== "point"
  ) {
    return undefined;
  }
  const target = action.interaction.target;
  if (target.identifier) return `page.locator(${JSON.stringify(`[id="${target.identifier}"]`)})`;
  if (target.label) return `page.getByRole("generic", { name: ${JSON.stringify(target.label)} })`;
  return undefined;
}

function stepFor(action: GoalSessionAction): string | undefined {
  const interaction = action.interaction;
  if (interaction.kind === "fill") {
    const selector = selectorFor(action);
    if (!selector) {
      return `    // TODO: fill "${action.label}" — Relay recorded no stable selector for this field.`;
    }
    return `    await ${selector}.fill(${JSON.stringify(interaction.value)});`;
  }
  if (interaction.kind === "key") {
    if (interaction.key !== "back") {
      return `    // TODO: system key "${interaction.key}" has no direct Playwright mapping here.`;
    }
    return `    await page.goBack();`;
  }
  if (interaction.kind === "swipe") {
    return `    await page.mouse.move(${interaction.from.x}, ${interaction.from.y});\n    await page.mouse.down();\n    await page.mouse.move(${interaction.to.x}, ${interaction.to.y});\n    await page.mouse.up();`;
  }
  if (interaction.kind === "wait") {
    return `    await page.waitForTimeout(${Math.min(interaction.ms, 10_000)});`;
  }
  if (interaction.kind === "capture") {
    return `    await page.screenshot({ path: ${JSON.stringify(`relay-${action.id}.png`)} }); // Review manually: a screenshot is not an assertion.`;
  }
  const selector = selectorFor(action);
  if (selector) return `    await ${selector}.click();`;
  if (interaction.kind === "point") {
    return `    await page.mouse.click(${interaction.target.point?.x ?? 0}, ${interaction.target.point?.y ?? 0}); // Coordinate fallback: verify stability yourself.`;
  }
  return `    // TODO: action "${action.label}" used a selector form Playwright cannot map directly.`;
}

export function exportGoalSessionPlaywrightSpec(record: GoalSessionRecord): string {
  if (record.target.platform !== "browser") {
    throw new TypeError("Playwright export requires a browser goal path.");
  }
  const acknowledged = record.actions.filter((action) => action.status === "acknowledged");
  if (acknowledged.length === 0) {
    throw new TypeError("Playwright export requires at least one acknowledged action.");
  }
  const startUrl = record.target.startUrl;
  if (!startUrl) {
    throw new TypeError("Playwright export requires the goal's durable startUrl.");
  }
  const accountNote = record.target.authenticationFixtureReference
    ? `  // Relay used account fixture ${record.target.authenticationFixtureReference}.\n  // Supply the equivalent storageState yourself; identity claims do not export.`
    : "  // Relay ran this path signed out.";
  const body = acknowledged
    .map((action) => stepFor(action) ?? `    // TODO: unmapped action ${action.id}.`)
    .join("\n");
  return `${HEADER}
test(${JSON.stringify(record.goal.slice(0, 120))}, async ({ page }) => {
${accountNote}
  await page.goto(${JSON.stringify(startUrl)});
${body}
});
`;
}
