import { readFile } from "node:fs/promises";
import { HttpError } from "./http.js";

const SCRCPY_SERVER_VERSION = "2.5";
const PREPARATION_MESSAGE =
  'Android live preview needs the scrcpy 2.5 server asset. Run "npm exec -- fetch-scrcpy-server 2.5" in the Relay installation, then restart Relay and retry live preview.';

type AndroidVideoServerDependencies = {
  importAssets: () => Promise<unknown>;
  readBinary: (path: URL) => Promise<Buffer>;
};

const dependencies: AndroidVideoServerDependencies = {
  importAssets: () => import("@yume-chan/fetch-scrcpy-server"),
  readBinary: readFile,
};

/** The package exports are generated by Android setup. Browser startup must
 * not import them, and an Android request must fail before opening ADB when
 * setup has not supplied the pinned server binary. */
export async function readAndroidVideoServer(
  io: AndroidVideoServerDependencies = dependencies,
): Promise<{ binary: Buffer; version: string }> {
  try {
    const assets = await io.importAssets();
    if (
      !assets ||
      typeof assets !== "object" ||
      !("BIN" in assets) ||
      !(assets.BIN instanceof URL) ||
      assets.BIN.protocol !== "file:" ||
      !("VERSION" in assets) ||
      assets.VERSION !== SCRCPY_SERVER_VERSION
    ) {
      throw new Error("Android server assets are not prepared");
    }
    const binary = await io.readBinary(assets.BIN);
    if (binary.byteLength === 0) throw new Error("Android server binary is empty");
    return { binary, version: SCRCPY_SERVER_VERSION };
  } catch {
    throw new HttpError(503, PREPARATION_MESSAGE);
  }
}
