/**
 * Accessibility identifiers are engineering handles, not product copy. They are
 * still the only clue about what a control is when a screen recorded no visible
 * label, so chrome shows the words inside one rather than the raw token:
 * `ai.x.grok:id/settings_button` is a Settings control, not a settings_button
 * element.
 */

/** Android resource ids arrive fully qualified: `com.example.app:id/name`. */
const RESOURCE_PREFIX = /^[a-z][\w.]*:id\//i;

/** Words that name the widget rather than the thing a person is looking for. */
const WIDGET_NOISE = new Set([
  "btn",
  "button",
  "cell",
  "container",
  "control",
  "icon",
  "id",
  "image",
  "img",
  "item",
  "iv",
  "layout",
  "row",
  "tv",
  "txt",
  "view",
  "wrapper",
]);

/** A token nobody typed on purpose: a hash, a uuid, an autogenerated ref. */
function opaque(token: string): boolean {
  if (token.length > 24) return true;
  if (/^[0-9a-f]{8,}$/i.test(token)) return true;
  return /^\d+$/.test(token);
}

/**
 * Plain words hiding inside an identifier, or null when there is nothing a
 * person would recognise. Callers must treat null as "say nothing about the
 * target" rather than falling back to the raw token.
 */
export function humanizeIdentifier(raw: string | undefined | null): string | null {
  const value = raw?.trim();
  if (!value) return null;
  const words = value
    .replace(RESOURCE_PREFIX, "")
    .replace(/[._:/\-\s]+/g, " ")
    .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
    .trim()
    .split(" ")
    .filter((word) => word && !opaque(word))
    .map((word) => (/^[A-Z0-9]{2,}$/.test(word) ? word : word.toLowerCase()));
  if (!words.length) return null;
  const meaningful = words.filter((word) => !WIDGET_NOISE.has(word));
  const kept = meaningful.length ? meaningful : [];
  if (!kept.length) return null;
  const phrase = kept.join(" ");
  return phrase.charAt(0).toLocaleUpperCase() + phrase.slice(1);
}

/**
 * Whether a string is a handle rather than a name. Titles reach the canvas from
 * recordings as well as from people, so a screen can end up called
 * `settings_button`; but "Customize Grok" and "NSFW Preferences" are names
 * somebody chose and must survive untouched. Only unspaced tokens that carry a
 * separator or a camel hump qualify.
 */
export function looksLikeIdentifier(value: string | undefined | null): boolean {
  const token = value?.trim();
  if (!token || /\s/.test(token)) return false;
  return RESOURCE_PREFIX.test(token) || /[._:/]/.test(token) || /[a-z0-9][A-Z]/.test(token);
}

/**
 * A screen title fit to print. Falls back to the stored title whenever the
 * identifier holds nothing recognisable, so a screen never loses its name.
 */
export function humanizeTitle(title: string): string {
  if (!looksLikeIdentifier(title)) return title;
  return humanizeIdentifier(title) ?? title;
}

/**
 * How to name a target that has no visible label. "control" keeps the sentence
 * honest: the words came from an identifier, so they are not text a person can
 * read on the screen and must never be quoted as if they were.
 */
export function identifierControlPhrase(identifier: string | undefined | null): string | null {
  const name = humanizeIdentifier(identifier);
  return name ? `the ${name} control` : null;
}
